-- First, remove the bookmark if it exists
drop table if exists bookmarks;

-- Create the bookmark anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url_ text,
  description_ text,
  rating INTEGER
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url_, description_, rating)
values
  ('Portfolio', 'http://www.tyleralder.com', 'tylers portfolio', 5),
  ('Google', 'http://www.google.com', 'google search engine', 5),
  ('Thinkful', 'http://www.thinkful.com', 'thinkful coding bootcamp', 5),
  ('Reddit', 'http://www.reddit.com', 'an aweful place', 1),
  ('Bing', 'http://www.bing.com', 'why does this exist?', 1),
  ('Twitter', 'http://www.twitter.com', 'share thoughts with the world', 4),
  ('Facebook', 'http://www.facebook.com', 'stay in touch with your mom', 3),
  ('Marine Corps', 'http://www.marines.mil', 'see the world, kill things.', 3),
  ('Apple', 'http://www.apple.com', 'our customers dont know what they want', 1),
  ('Android', 'http://www.android.com', 'the platform pushing whats possible', 3);
  